---
name: Robert
surname: Wiederstein
position: "Developer • Programmer • Analyst"
address: "910 Powhatan, Unit 106S, Alexandria, VA 22314"
#phone: 270.869.5112
www: robwiederstein.org
email: "robwiederstein@protonmail.com"
twitter: RobWiederstein
github: RobWiederstein
#linkedin: <a href='https://www.linkedin.com/in/rob-wiederstein-797553138/'>rob-wiederstein</a>
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
headcolor: 3026ef
profilepic: pic.jpg
csl: numeric-apa-cv.csl
docname: CV/Resume
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(glue)
library(myCV)
library(tibble)
```

# Summary

I have been programming in R for the past seven years. My experiences and interests are diverse, detailed in my [**blog**](https://www.robwiederstein.org) and maintained in my GitHub [**repository**](https://github.com/RobWiederstein). I enjoy traveling, reading, playing guitar and cooking family meals.


```{r load-data, include=FALSE}
jobs <- readr::read_csv("../data/jobs.csv")
schools <- readr::read_csv("../data/schools.csv")
skills <- readr::read_csv("../data/skills.csv")
```

# Education

```{r education, echo=FALSE}
detailed_entries(schools, 
                 when = glue("{start_date}--{end_date}"),
                 what = degree,
                 where = loc,
                 with = uni)
```

# Work

```{r work}
jobs %>% 
  detailed_entries(
    what = role,
    when = glue("{start_date}--{end_date}"),
    with = company,
    where = where,
    why = details)
```

# Skills

```{r skills}
skills %>%
    vitae::detailed_entries(
        with = familiar,
        what = skills
    )
```

# Application Software

```{r software, eval=T}
tribble(
  ~ pkg, ~ when, ~ role, ~ details,
  'buildingBlocks', '2022', 'In production', 'A dashboard of significant childhood development milestones with an emphasis on the role of high quality childcare, pre-k, and health on future educational outcomes. Data sources include the Internal Revenue Service, Bureau of Labor Statistics and the Indiana Department of Education.  US Census Bureau GIS data were also included for county and school district boundaries.',
  'econdash', '2022', 'In production', 'A dashboard of significant economic indicators from the U.S. Federal Reserve, International Monetary Fund, and the Organization For Economic Cooperation and Development.',
  'sarasota', '2022', 'Developer/author', 'A dashboard on Sarasota County residential real estate prices including both condominiums and single family homes.', 
  'retirementDash', '2021', 'Developer/author', 'A dashboard of retirement locations filtered by health, environment, housing affordability, and demographic criteria. An inter-county migration dataset was also included.',
  'retirementData', '2021', 'Developer/author', 'The dataset provides demographic, economic, environmental, and health data by county to determine retirement location. All United States counties are included.',
  'KeyWestMopeds', '2021', 'Developer/author', 'The package explores motorcycle crash data from 2012 through 2021 furnished via the Florida Highway Safety and Motor Vehicle Department through its open data portal.'
) %>% 
  brief_entries(glue::glue("\\textbf{<pkg>}: <role> \\newline <details>", .open = "<", .close = ">"), paste0(when, "\\newline"), .protect = FALSE)

```
# Publications

```{r Publications}
#bibliography_entries("pubs.bib")
bibliography_entries("pubs.bib")
```

# Packages Used

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble", "glue", "myCV"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

